services:
  web:
    image: ssamantle-web-client:dev
    container_name: ssamantle-web-client-dev
    build:
      context: .
      args:
        PUBLIC_URL: ${PUBLIC_URL:-.}
        API_BASE_URL: ${API_BASE_URL:-}
        USE_MOCK_API: ${USE_MOCK_API:-false}
    ports:
      - "80:80"
    environment:
      APP_BASE_PATH: ${APP_BASE_PATH:-}
